### PR TITLE
fix setup.py

### PR DESCRIPTION
**Pull request by graingert**

### CODE REVIEW

**Comment by sdunster** [comment]
`setup.py check` appears to be failing on travis but it's showing for a merge commit that is not on this PR so I don't get it...

**Comment by graingert** [comment]
@cenalulu Ah it's a known issue with travis's version of 3.3

**Comment by cenalulu** [comment]
@graingert Could you please also add an inline comment to travis.yml pointing to the page that explains the known issue? 
Apart from that the PR looks all good. I'll port it into our repo and re-sync back.

**Comment by graingert** [comment]
@cenalulu fyi: https://github.com/travis-ci/travis-ci/issues/7028#issuecomment-267115326

**Comment by graingert** [comment]
@cenalulu I've added this now.

**Pull request closed without merging**
